CC	= gcc

FUNC_0	= movie 
FUNC_1	= addData
FUNC_2	= codeGen
FUNC_3	= deletion
FUNC_4	= displayData
FUNC_5	= editFunction
FUNC_6	= ioFunction
FUNC_7	= movieValidate
FUNC_8	= search
FUNC_9	= writeData

PATH_0	= ./$(FUNC_0)/$(FUNC_0)
PATH_1	= ./$(FUNC_1)/$(FUNC_1)
PATH_2	= ./$(FUNC_2)/$(FUNC_2)
PATH_3	= ./$(FUNC_3)/$(FUNC_3)
PATH_4	= ./$(FUNC_4)/$(FUNC_4)
PATH_5	= ./$(FUNC_5)/$(FUNC_5)
PATH_6	= ./$(FUNC_6)/$(FUNC_6)
PATH_7	= ./$(FUNC_7)/$(FUNC_7)
PATH_8	= ./$(FUNC_8)/$(FUNC_8)
PATH_9	= ./$(FUNC_9)/$(FUNC_9)

ALL	= 
all	: 
